[package]
name = "sleep_disable_switcher"
version = "0.1.0"
authors = ["dumra"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
